-- COMANDO PARA CRIAR BANCO DE DADOS
CREATE DATABASE BIBLIOTECA_OTAVIO;
CREATE DATABASE BIBLIOTECA_OTAVIO2;

-- COMANDO PARA APAGAR BANCO DE DADOS
DROP DATABASE BIBLIOTECA_OTAVIO2;

-- COMANDO PARA ATIVAR BANCO DE DADOS
USE BIBLIOTECA_OTAVIO;

-- COMANDO PARA CRIAR TABELAS
CREATE TABLE CLIENTES (
ID_CLIENTES INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
EMAIL VARCHAR(60),
IDADE INT NOT NULL,
TELEFONE VARCHAR(14),
STATUS_CLIENTE VARCHAR(10) DEFAULT "ATIVO",
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE FUNCIONARIOS (
ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
SALARIO DECIMAL(5,2),
DATA_ADMISSAO DATE
);

-- COMANDO PARA APAGAR TABELAS
DROP TABLE FUNCIONARIOS;
