-- COMENTÁRIOS
-- COMANDO PARA CRIAR BANCO DE DADOS
CREATE DATABASE EXEMPLO;

-- APAGAR BANCO DE DADOS
DROP DATABASE EXEMPLO;

-- APAGAR TABELAS DO BANCO
DROP TABLE CLIENTES;

-- ATIVAR BANCO DE DADOS
USE EXEMPLO;

-- CRIAR TABELAS
CREATE TABLE CLIENTES (
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
ENDERECO VARCHAR(60) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
TELEFONE VARCHAR(15) NOT NULL 
);




