-- COMANDO PARA CRIAR BD
-- 1
CREATE DATABASE ACADEMIA_ADRYAN;
CREATE DATABASE IF NOT EXISTS ACADEMIA_ADRYAN;

-- 2
-- ATUALIZAR SCHEMAS

-- COMANDO PARA ATIVAR BD
-- 3
USE ACADEMIA_ADRYAN;

-- COMANDO PARA APAGAR BD
DROP DATABASE ACADEMIA_ADRYAN;
-- COMANDO PARA APAGAR TABELA
DROP TABLE CLIENTES; 

-- COMANDO CRIAR TABELA
CREATE TABLE IF NOT EXISTS CLIENTES (
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
CPF VARCHAR(14) NOT NULL UNIQUE,
NOME VARCHAR(60) NOT NULL,
TELEFONE VARCHAR(15) NOT NULL,
ENDERECO VARCHAR(100),
DATA_NASCIMENTO DATE NOT NULL,
STATUS_CLIENTE ENUM ("PENDENTE", "ATIVO", 'INATIVO') DEFAULT 'PENDENTE',
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PLANOS (
ID_PLANO INT AUTO_INCREMENT PRIMARY KEY,
NOME_PLANO VARCHAR(20) NOT NULL,
TIPOS_PLANO CHAR(10) DEFAULT "MENSAL",
VALOR DECIMAL(5,2) DEFAULT 0.00,
ADICIONAIS CHAR(10) DEFAULT "EXAME",
OBSERVACAO TEXT
);

-- COMANDOS PARA ALTERAR E CORRIGIR
-- ADICIONANDO UM CAMPO (ATRIBUTO) NOVO
ALTER TABLE CLIENTES ADD EMAIL VARCHAR(100);

-- MODIFICAR TIPO DE DADOS OU CAMPOS
ALTER TABLE CLIENTES MODIFY EMAIL VARCHAR(150);

-- RENOMEAR TABELAS
RENAME TABLE CLIENTES TO CLIENTESS;

-- EXCLUIR ATRIBUTO
ALTER TABLE CLIENTESS DROP COLUMN EMAIL;

-- VISUALIZAR TABELAS NO BD
SHOW TABLES;

-- LIMPAR DADOS DA TABELA
TRUNCATE TABLE CLIENTES;

-- INSERIR DADOS NO BD
INSERT INTO clientes (ID_CLIENTE, NOME, CPF, TELEFONE, ENDERECO, DATA_NASCIMENTO, STATUS_CLIENTE, DATA_CADASTRO) 
VALUES ('BRUNO', '123.456.789-78', '(19)9 7894-4561', 'RUA SENAI', '2013-13-13', 'ATIVO');

CREATE TABLE FUNCIONARIOS (
   ID_FUNCIONARIO INT PRIMARY KEY,
   EMAIL VARCHAR(255) UNIQUE
);

-- COMANDO PARA INSERIR DADOS NO BD
INSERT INTO FUNCIONARIOS (ID_FUNCIONARIO, EMAIL)
VALUES (2,'ANNA@SENAI.COM.BR');

INSERT INTO FUNCIONARIOS (ID_FUNCIONARIO, EMAIL)
VALUES (3,'ANNA@SENAI.COM.BR');


-- COMANDO PARA CONSULTAR INFORMAÇÕES NA TABELA
SELECT * FROM FUNCIONARIOS;



