-- COMANDOS PARA CRIAR BD
-- 1
CREATE DATABASE CLINICA_MEDICA_KEYNAN;
CREATE DATABASE IF NOT EXISTS CLINICA_MEDICA_KEYNAN;

CREATE DATABASE BANCO_DADOS;

-- ATIVAR BD E ATUALIZAR SCHEMAS
-- 2
USE CLINICA_MEDICA_KEYNAN;

-- CRIAR TABELAS
-- 3
CREATE TABLE IF NOT EXISTS PACIENTES (
ID_PACIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOME_PACIENTE VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
DATA_NASCIMENTO DATE NOT NULL,
EMAIL VARCHAR(100),
TELEFONE VARCHAR(15), 
CONVENIO ENUM ('SIM', 'NÃO') NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
ID_FUNCIONARIO INT PRIMARY KEY,
NOME_FUNCIONARIO VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,   
TELEFONE VARCHAR(15) ,
SALARIO DECIMAL(5,2) DEFAULT 0.00
);




-- ALTERAR INFORMAÇÕES DA TABELA
-- ALTER TABLE
-- ADICIONAR UM CAMPO (ATRIBUTO) OU COLUNA NA TABELA
ALTER TABLE FUNCIONARIOSS ADD EMAIL VARCHAR(100) NOT NULL;

-- ALTERAR TIPO DE DADOS DE CAMPO (ATRIBUTO) OU COLUNA NA TABELA
ALTER TABLE FUNCIONARIOS MODIFY EMAIL VARCHAR(50) NOT NULL;

-- APAGAR O CAMPO (ATRIBUTO) OU COLUNA NA TABELA
ALTER TABLE FUNCIONARIOS DROP COLUMN EMAIL;

-- RENOMEAR TABELAS
RENAME TABLE FUNCIONARIOS TO FUNCIONARIOSS;
RENAME TABLE FUNCIONARIOSS TO FUNCIONARIOS;

-- APAGAR DADOS DA TABELA
TRUNCATE TABLE PACIENTES;

-- ---------------------------------------------
-- USAR COM RESPONSABILIDADE !!
-- APAGAR BD
DROP DATABASE CLINICA_MEDICA_KEYNAN;
-- APAGAR TABELAS
DROP TABLES FUNCIONARIOS;

-- MOSTRAR TABELAS NO BD
SHOW TABLES;

-- MOSTRAR TODOS OS BD 
SHOW DATABASES;

-- -----------------------------------------

-- INSERIR DADOS NO BD
INSERT INTO FUNCIONARIOS (ID_FUNCIONARIO,NOME_FUNCIONARIO,CPF,TELEFONE,SALARIO)
VALUES (2,'LIVIA','124.478.854-13','(19)98013-0501',999),
(3,'LUCAS','251.123.456-78','(11)91239-0123', 300);

INSERT INTO PACIENTES (ID_PACIENTE,NOME_PACIENTE,
CPF,DATA_NASCIMENTO,EMAIL,TELEFONE,CONVENIO)
VALUES (DEFAULT,'BRUNO','123.456.789-78','1983-10-23',
'bruno@senai.br','12 1234 4678','SIM');
-- PADRÃO PARA DATA ANO-MÊS-DIA


-- CONSULTAR DADOS NO BD
SELECT * FROM PACIENTES;



















